using System;
using System.IO;
using System.Text;

namespace SourceCodeGenerator;

/// <summary>
/// A practical source code generator that creates C# model classes from JSON schemas.
/// Demonstrates reflection, code generation, and file I/O.
/// </summary>
class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("=== C# Source Code Generator ===\n");
        Console.WriteLine("Generates C# model classes from JSON input.\n");

        // Sample JSON input for demonstration
        string sampleJson = """
            {
                "name": "John Doe",
                "age": 30,
                "email": "john@example.com",
                "isActive": true,
                "scores": [1, 2, 3]
            }
            """;

        Console.WriteLine("Sample JSON input:");
        Console.WriteLine(sampleJson);
        Console.WriteLine();

        // Generate C# class from JSON
        string className = "UserModel";
        string generatedCode = GenerateClassFromJson(sampleJson, className);

        Console.WriteLine("Generated C# Class:");
        Console.WriteLine(generatedCode);
        Console.WriteLine();

        // Save to file
        string outputPath = Path.Combine(Directory.GetCurrentDirectory(), $"{className}.cs");
        File.WriteAllText(outputPath, generatedCode);
        Console.WriteLine($"✓ Class saved to: {outputPath}");

        // Generate multiple classes example
        Console.WriteLine("\n--- Generating Multiple Classes ---\n");
        GenerateMultipleClasses();
    }

    static string GenerateClassFromJson(string json, string className)
    {
        var properties = new StringBuilder();

        // Simple JSON parsing (for demonstration - use System.Text.Json in production)
        var cleanedJson = json.Trim('{', '}').Trim();
        var pairs = SplitJsonProperties(cleanedJson);

        foreach (var pair in pairs)
        {
            var parts = pair.Split(':', 2);
            if (parts.Length != 2) continue;

            var propName = parts[0].Trim().Trim('"');
            var propValue = parts[1].Trim();

            // Determine type from value
            string propType = propValue switch
            {
                var v when v.StartsWith('[') => "List<object>",
                var v when v.StartsWith('"') => "string",
                var v when v.Equals("true", StringComparison.OrdinalIgnoreCase) ||
                           v.Equals("false", StringComparison.OrdinalIgnoreCase) => "bool",
                var v when int.TryParse(v, out _) => "int",
                var v when double.TryParse(v, out _) => "double",
                _ => "object"
            };

            // Handle arrays
            if (propValue.StartsWith('['))
            {
                var arrayContent = propValue.Trim('[', ']').Trim();
                if (int.TryParse(arrayContent.Split(',').FirstOrDefault()?.Trim(), out _))
                {
                    propType = "List<int>";
                }
                else if (arrayContent.StartsWith('"'))
                {
                    propType = "List<string>";
                }
            }

            properties.AppendLine($"    public {propType} {propName} {{ get; set; }}");
        }

        var result = new StringBuilder();
        result.AppendLine("// Auto-generated by SourceCodeGenerator");
        result.AppendLine("using System;");
        result.AppendLine("using System.Collections.Generic;");
        result.AppendLine();
        result.AppendLine($"public class {className}");
        result.AppendLine("{");
        result.Append(properties);
        result.AppendLine("}");
        
        return result.ToString();
    }

    static List<string> SplitJsonProperties(string json)
    {
        var result = new List<string>();
        var depth = 0;
        var current = new StringBuilder();

        foreach (var c in json)
        {
            if (c == '{' || c == '[') depth++;
            if (c == '}' || c == ']') depth--;

            if (c == ',' && depth == 0)
            {
                result.Add(current.ToString().Trim());
                current.Clear();
            }
            else
            {
                current.Append(c);
            }
        }

        if (current.Length > 0)
            result.Add(current.ToString().Trim());

        return result;
    }

    static void GenerateMultipleClasses()
    {
        // Generate a set of related classes
        var outputDir = Directory.GetCurrentDirectory();

        string entityClass = """
            // Auto-generated Entity base class
            using System;

            public abstract class Entity
            {
                public int Id { get; set; }
                public DateTime CreatedAt { get; set; }
                public DateTime? UpdatedAt { get; set; }

                protected Entity()
                {
                    CreatedAt = DateTime.UtcNow;
                }
            }
            """;

        string repositoryInterface = """
            // Auto-generated Repository interface
            using System;
            using System.Collections.Generic;
            using System.Threading.Tasks;

            public interface IRepository<T> where T : Entity
            {
                Task<T> GetByIdAsync(int id);
                Task<IEnumerable<T>> GetAllAsync();
                Task<T> AddAsync(T entity);
                Task UpdateAsync(T entity);
                Task DeleteAsync(int id);
            }
            """;

        File.WriteAllText(Path.Combine(outputDir, "Entity.cs"), entityClass);
        File.WriteAllText(Path.Combine(outputDir, "IRepository.cs"), repositoryInterface);

        Console.WriteLine("✓ Generated Entity.cs");
        Console.WriteLine("✓ Generated IRepository.cs");
    }
}
