using System;
using System.IO;
using System.Reflection;
using System.Runtime.Loader;

namespace AssemblyResolver;

/// <summary>
/// Demonstrates custom assembly resolution and dynamic loading.
/// Shows how to load assemblies from custom locations and handle dependencies.
/// </summary>
class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("=== Assembly Resolver Demo ===\n");
        Console.WriteLine("Demonstrates custom assembly loading and resolution.\n");

        // Demo 1: Assembly loading contexts
        Console.WriteLine("--- Assembly Load Contexts ---\n");
        AssemblyContextsDemo();

        // Demo 2: Custom assembly resolver
        Console.WriteLine("\n--- Custom Assembly Resolver ---\n");
        CustomResolverDemo();

        // Demo 3: Dynamic type loading
        Console.WriteLine("\n--- Dynamic Type Loading ---\n");
        DynamicTypeLoadingDemo();

        // Demo 4: Assembly information
        Console.WriteLine("\n--- Loaded Assemblies ---\n");
        ListLoadedAssemblies();
    }

    static void AssemblyContextsDemo()
    {
        // Default context
        var defaultContext = AssemblyLoadContext.Default;
        Console.WriteLine($"Default context: {defaultContext.Name}");
        Console.WriteLine($"Is default: {defaultContext == AssemblyLoadContext.Default}");

        // Create custom context
        var customContext = new CustomLoadContext();
        Console.WriteLine($"\nCustom context created: {customContext.Name}");

        // Load assembly in custom context
        try
        {
            var systemJson = customContext.LoadFromAssemblyName(new AssemblyName("System.Text.Json"));
            Console.WriteLine($"Loaded System.Text.Json in custom context");
            Console.WriteLine($"  Version: {systemJson.GetName().Version}");
            Console.WriteLine($"  Location: {systemJson.Location}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Could not load: {ex.Message}");
        }

        // Unload custom context
        customContext.Unload();
        Console.WriteLine("\nCustom context unloaded");
    }

    static void CustomResolverDemo()
    {
        // Register custom resolver
        var resolver = new CustomAssemblyResolver();
        AssemblyLoadContext.Default.Resolving += resolver.OnResolving;

        Console.WriteLine("Custom resolver registered");
        Console.WriteLine($"Search paths: {string.Join(", ", resolver.SearchPaths)}");

        // Simulate assembly load
        Console.WriteLine("\nAttempting to resolve assemblies...");
        
        // Unregister
        AssemblyLoadContext.Default.Resolving -= resolver.OnResolving;
        Console.WriteLine("\nCustom resolver unregistered");
    }

    static void DynamicTypeLoadingDemo()
    {
        // Load from current assembly
        var currentAssembly = Assembly.GetExecutingAssembly();
        Console.WriteLine($"Current assembly: {currentAssembly.GetName().Name}");

        // Find and instantiate types
        var types = currentAssembly.GetTypes();
        Console.WriteLine($"\nTypes in current assembly:");
        
        foreach (var type in types)
        {
            if (!type.IsInterface && !type.IsAbstract)
            {
                Console.WriteLine($"  - {type.Name}");
                
                // Try to create instance if it has default constructor
                var constructor = type.GetConstructor(Type.EmptyTypes);
                if (constructor != null)
                {
                    try
                    {
                        var instance = Activator.CreateInstance(type);
                        Console.WriteLine($"    ✓ Instance created");
                    }
                    catch
                    {
                        Console.WriteLine($"    ✗ Cannot create instance");
                    }
                }
            }
        }

        // Load from stream (simulated)
        Console.WriteLine("\n--- Loading from Stream ---");
        LoadFromStreamDemo();
    }

    static void LoadFromStreamDemo()
    {
        // In real scenario, you'd load from a file or network stream
        // This demonstrates the API
        Console.WriteLine("Stream loading demonstration:");
        Console.WriteLine("  AssemblyLoadContext.LoadFromStream() can load from:");
        Console.WriteLine("  - Network streams");
        Console.WriteLine("  - Encrypted assemblies");
        Console.WriteLine("  - Dynamically generated bytecode");
        Console.WriteLine("  - In-memory assemblies");
    }

    static void ListLoadedAssemblies()
    {
        var assemblies = AppDomain.CurrentDomain.GetAssemblies();
        
        Console.WriteLine($"Total loaded assemblies: {assemblies.Length}\n");
        
        var sorted = assemblies.OrderBy(a => a.GetName().Name);
        
        foreach (var assembly in sorted.Take(20)) // Show first 20
        {
            var name = assembly.GetName();
            Console.WriteLine($"{name.Name,-40} v{name.Version?.ToString() ?? "N/A"}");
        }

        if (assemblies.Length > 20)
        {
            Console.WriteLine($"... and {assemblies.Length - 20} more");
        }
    }
}

/// <summary>
/// Custom assembly load context for isolation
/// </summary>
public class CustomLoadContext : AssemblyLoadContext
{
    public CustomLoadContext() : base("CustomContext", isCollectible: true)
    {
    }

    protected override Assembly? Load(AssemblyName assemblyName)
    {
        // Try to load from custom location
        Console.WriteLine($"  CustomContext loading: {assemblyName.Name}");
        return null; // Let default resolver handle it
    }
}

/// <summary>
/// Custom assembly resolver for handling missing dependencies
/// </summary>
public class CustomAssemblyResolver
{
    public List<string> SearchPaths { get; } = new()
    {
        Directory.GetCurrentDirectory(),
        Path.Combine(Directory.GetCurrentDirectory(), "plugins"),
        Path.Combine(Directory.GetCurrentDirectory(), "libs")
    };

    public Assembly? OnResolving(AssemblyLoadContext context, AssemblyName assemblyName)
    {
        Console.WriteLine($"  Resolving: {assemblyName.Name}");

        foreach (var path in SearchPaths)
        {
            var assemblyPath = Path.Combine(path, $"{assemblyName.Name}.dll");
            if (File.Exists(assemblyPath))
            {
                Console.WriteLine($"    Found at: {assemblyPath}");
                return context.LoadFromAssemblyPath(assemblyPath);
            }
        }

        Console.WriteLine($"    Not found in custom paths");
        return null;
    }
}

/// <summary>
/// Sample class for type loading demonstration
/// </summary>
public class SamplePlugin
{
    public string Name => "SamplePlugin";
    
    public void Execute()
    {
        Console.WriteLine("  Plugin executed!");
    }
}
